2d ed fix and update
SND-LHC/sndsw pull request #196
Opened 2024-01-31 10:08 UTC by siilieva

- fix canvas drawing in the 2dED
- read event info straight from the event header and not the run_timestamps.json stored with the raw data. This is especially important in the prospect of deleting the archived /raw_data from EOS to free up space.

2024-01-31 10:38 UTC, olantwin requested changes
Looks good to me.

Two nitpicks:

* See my comment on the import order
* The first lines of the commit messages are too long. They should be ideally less than 50 characters. Additional explanation can be added after a blank line.

:+1: for making very small changes that are super easy to review!

2024-01-31 10:38 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
Is the matplotlib import hidden in SndlhcMuonReco?

This is not good...

Is it understood why this import order is necessary?

2024-01-31 11:54 UTC, siilieva commented on shipLHC/scripts/2dEventDisplay.py
The matplotlib module is only needed for the SndlhcMuonReco and if a flag is set to true(drawing of the filled Hough space map). Since SndlhcMuonReco can be run standalone, the module is imported there. In this sense, it is not hidden.
Online there are a lot of conflict reports with matplotlib and other py modules observed across various platforms. Apparently, it is a reoccurring issue. I don't exactly know what is messed up btw matplotlib and rootUtils on rhel9.

2024-01-31 12:32 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
In that case, it might be best to only import that module if the drawing option is enabled.

2024-01-31 13:11 UTC, siilieva commented on shipLHC/scripts/2dEventDisplay.py
Good. I don't like it when there are imports in between code, but since matplotlib is a trouble maker, I agree with this proposal. I'll test to verify nothing breaks doing so.

2024-01-31 13:22 UTC, siilieva commented on shipLHC/scripts/2dEventDisplay.py
Ah, moving the _import matplotlib_  to the tracking task init() and executing only if flag is 1 makes the display issue reappear if the flag = 1. Of course! The whole point is that rootUtils is imported *after* matplotlib and it wont be the case for flag=1. So the order and realization must stay as in the original commit.

2024-01-31 13:25 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
Yes, I think the reordering and hiding the import behind the flag are necessary.

It might also be good to set the flag only via the command line (so that it's not set when used by e.g. the event display), instead of via the tracking config.

2024-01-31 13:39 UTC, siilieva commented on shipLHC/scripts/2dEventDisplay.py
The flag(<draw> flag to be precise)  is set in the TrackingParams.xml. Loading of a given/custom xml is controlled by the command line for both the standalone tracking and the 2dED.
It is extremely useful to use the 2dED with the <draw> flag on - one sees both the display and its view in the Hough space. 
To me,  it is best to keep things as they are.

2024-02-01 13:03 UTC, siilieva commented
@olantwin, what is left to be done here? Is it the commit messages length?

2024-02-01 13:17 UTC, olantwin commented
> @olantwin, what is left to be done here? Is it the commit messages length?

If you could reword them into a short summary and further information after a blank line, that would be great.

2024-02-01 14:30 UTC, siilieva commented
> > @olantwin, what is left to be done here? Is it the commit messages length?
> 
> If you could reword them into a short summary and further information after a blank line, that would be great.

I tried :D

2024-02-01 14:32 UTC, olantwin approved these changes
Grazie per la sua collaborazione!

2024-02-01 14:33 UTC, olantwin commented
> > > @olantwin, what is left to be done here? Is it the commit messages length?
> > 
> > 
> > If you could reword them into a short summary and further information after a blank line, that would be great.
> 
> I tried :D

The rhel9 is still a tad long, but practice makes perfect. Good enough for this trivial change :)

2024-02-01 14:33 UTC, merged