Restore scifi clusters mc
SND-LHC/sndsw pull request #199
Opened 2024-02-02 10:07 UTC by siilieva

- bring back Scifi cluster making for the run_digi task
- restructure the reverted commits (includes comment cleaning)
- add option to run digi without making the clusters (by default clusters will be created)

! Sorting out the cluster-making issue #198 is beyond the intended scope of this PR.

2024-02-02 10:59 UTC, olantwin requested changes
* I don't understand why ff0d56b1fc71ec27ff9f4d37407252f6c869c98e was reverted, us you redo the changes of the reverted commit in 7a1b236f2ebcfccb29d7fc2dd9e8032877af80de.
* f8176d24554d8222ce1720fe6ea253ba7a9687e1 should be a fixup to e598f31e281848ecd4d251163ea51117f4cfedbf.

LGTM otherwise. Happy to defer general improvements to a future PR addressing #198 .

2024-02-02 10:59 UTC, olantwin commented on shipLHC/run_digiSND.py
> +parser.add_argument("-no-cls", "--noClusterScifi", action='store_true', dest="noClusterScifi", help="do not make Scifi clusters")
I would remove the short option here. Multi-character short options are quite unconventional.
For the long option, could we do kebab-case please? ;)
If we stick to `--noClusterScifi`, the `dest=` isn't needed, as it's automatically `noClusterScifi`.

2024-02-02 10:59 UTC, olantwin commented on sndFairTasks/DigiTaskSND.cxx
> +    if (fMakeClusterScifi) fScifiClusterArray->Delete();
This should be `Clear()` or `Clear('C')`, see Note 2 [here](https://root.cern/doc/master/classTClonesArray.html)

2024-02-02 10:59 UTC, olantwin commented on python/SndlhcDigi.py
> +           self.clusScifi.Delete()
This should be `Clear()` or `Clear('C')`, see Note 2 [here](https://root.cern/doc/master/classTClonesArray.html)

2024-02-02 11:51 UTC, siilieva commented
I restructured the commits for this PR as the task to remove the thresholds was unnecessarily split in two commits before.
Since restructuring was already hapening for the reason above, I made a new commit for the clear up.

2024-02-02 11:57 UTC, siilieva commented on shipLHC/run_digiSND.py
> +parser.add_argument("-no-cls", "--noClusterScifi", action='store_true', dest="noClusterScifi", help="do not make Scifi clusters")
I find the` no-<smth>` flags very clear, even if longer than optimal for a short option. Still, it is sure shorter than the long one here `noClusterScifi`:D
Here I am simply following the case style of the other options.
Ok for _dest_, will edit the commit shortly.

2024-02-02 11:58 UTC, siilieva commented on python/SndlhcDigi.py
> +           self.clusScifi.Delete()
same as above :+1:

2024-02-02 12:05 UTC, olantwin commented on shipLHC/run_digiSND.py
> +parser.add_argument("-no-cls", "--noClusterScifi", action='store_true', dest="noClusterScifi", help="do not make Scifi clusters")
Usually the convention is that the single-dash options are a single character. I'd rather have no short option in cases where this is not possible. We don't need short options for everything.

2024-02-02 12:40 UTC, olantwin commented on sndFairTasks/DigiTaskSND.cxx
> +    if (fMakeClusterScifi) fScifiClusterArray->Delete();
Great! I've actually wanted to make this change for a while, but never got around to it. Should reduce the time and memory needed for digitisation.

2024-02-02 12:44 UTC, olantwin commented
> I restructured the commits for this PR as the task to remove the thresholds was unnecessarily split in two commits before. Since restructuring was already hapening for the reason above, I made a new commit for the clear up.

Unless you want the reverts to remain exactly as is, I would still suggest just making f8176d24554d8222ce1720fe6ea253ba7a9687e1 and 7a1b236f2ebcfccb29d7fc2dd9e8032877af80de fixups to the respective reverts to clean up the history a bit.

Otherwise things look OK now.

2024-02-02 13:14 UTC, siilieva commented
> > I restructured the commits for this PR as the task to remove the thresholds was unnecessarily split in two commits before. Since restructuring was already hapening for the reason above, I made a new commit for the clear up.
> 
> Unless you want the reverts to remain exactly as is, I would still suggest just making [f8176d2](https://github.com/SND-LHC/sndsw/commit/f8176d24554d8222ce1720fe6ea253ba7a9687e1) and [7a1b236](https://github.com/SND-LHC/sndsw/commit/7a1b236f2ebcfccb29d7fc2dd9e8032877af80de) fixups to the respective reverts to clean up the history a bit.
> 
> Otherwise things look OK now.

I tried fixup-ing locally and it looks weird. I prefer the way we have currently with separate revert and modifications commits.

2024-02-02 13:49 UTC, olantwin approved these changes

2024-02-05 08:48 UTC, dcentanni commented
Dear Simona and Oliver, it looks OK to me. Thank you!

2024-02-05 08:53 UTC, merged