Option to draw hit markers with colour representing charge (calorimet…
SND-LHC/sndsw pull request #201
Opened 2024-02-19 17:44 UTC by cvilelahep

Veto/HCal/Muon system hit colour represents total QDC for that hit.
SciFi hit colour represents number of hits within +- 0.5 cm of the drawn hit.

Example of muon candidate with `hitColour = None`:
![image](https://github.com/SND-LHC/sndsw/assets/11177614/c5ddfb9e-4d5b-4095-ac5a-a94b74100205)

Same event with `hitColour = "q"`:

2024-02-19 21:48 UTC, olantwin commented
I'll comment in detail tomorrow.

First impressions:
1. It's a lot of code with many calculations. It might be good to split it up slightly into funtions and possibly multiple commits (e.g. one for the colour options, one for the legend and one for the additional information display).
2. Could we use a colourbar as a legend instead of individual points?
3. I'll definitely have a few nitpicks about formatting and readability ;)

2024-02-19 22:34 UTC, cvilelahep commented
Hi @olantwin,

> It's a lot of code with many calculations. It might be good to split it up slightly into funtions and possibly multiple commits (e.g. one for the colour options, one for the legend and one for the additional information display).
The calculation of the hit density should probably be done in the analysis SciFi Tools library. When that becomes available we can remove it from the event display code. There are no other calculations other than defining positions of text, etc.
Sorry for bundling everything into a single commit. I don't have time to split this into several commits.

> Could we use a colourbar as a legend instead of individual points?
This would be my preference, but I couldn't find a way of doing it, and I don't have time to work on this any further. It may not be the prettiest solution, but it does the job.

>Is there a way to set this option via the commandline? It seems one needs to modify the python script to turn it on, unless I missed something while skimming?
It would be trivial to grab this option from the CLI. The 2dEventDisplay script code is written in such a way that it pretty much has to be run in interactive mode (I use heredocs to get around this), so having it as an argument to `loopEvents` doesn't typically require modifying the script.

2024-02-20 10:28 UTC, olantwin commented
> > It's a lot of code with many calculations. It might be good to split it up slightly into funtions and possibly multiple commits (e.g. one for the colour options, one for the legend and one for the additional information display).
> 
> The calculation of the hit density should probably be done in the analysis SciFi Tools library. When that becomes available we can remove it from the event display code.

For now, could it be split into a function? It would make following the code a bit easier.

> There are no other calculations other than defining positions of text, etc. Sorry for bundling everything into a single commit. I don't have time to split this into several commits.
> 
> I'm not sure what is meant by "additional information display".

Sorry, my bad. I meant the purple text with QDC values etc. I don't use the 2dEventDisplay much, so naively assumed you were adding it.

> This PR only adds colour to the markers and the legend required to interpret those colours.
> 
> > Could we use a colourbar as a legend instead of individual points?
> 
> This would be my preference, but I couldn't find a way of doing it, and I don't have time to work on this any further. It may not be the prettiest solution, but it does the job.

Then let's maybe add an issue for that as a future improvement.
Again, making a function for calculating the legend might make the code somewhat easier to digest.

> > Is there a way to set this option via the commandline? It seems one needs to modify the python script to turn it on, unless I missed something while skimming?
> 
> It would be trivial to change the code to grab this option from the CLI. However, the 2dEventDisplay script code is written in such a way that it pretty much has to be run in interactive mode (I use heredocs to get around this), so having it as an argument to `loopEvents` doesn't typically require modifying the script.

I see. What do you mean by heredoc in this context?
May I suggest checking for `q` or `charge` as options?
It might be also good to add a docstring with the `hitColour` option documented (we can add documentation for the other options later @siilieva ). This documentation should show up, when people run in ipython interactively.

2024-02-20 10:41 UTC, olantwin requested changes
Apart from formatting changes and my general comments, this looks ok.

It would be great to have the hit density calculation and legend setup encapsulated into functions.

General formatting comment: It would be great to remove all the spaces before the colons after `if`, `else` and `for` statements. I've never seen that style in python.
Conversely, spaces are missing around nearly every operator, but that's a general issue in sndsw, so I don't insist on changing that here.

2024-02-20 10:41 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
> +ROOT.gStyle.SetPalette(ROOT.kViridis)
Do we need to change from `kBird`? I would prefer that we stick to the default defined in the style (with the default being something we can define in @dcentanni's SNDstyle).

2024-02-20 10:41 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
> +def loopEvents(start=0,save=False,goodEvents=False,withTrack=-1,withHoughTrack=-1,nTracks=0,minSipmMult=1,withTiming=False, option=None,Setup='',verbose=0,auto=False, hitColour = None):
Please remove the space around the `=` (PEP8).
It would be good to split this line and put every argument onto a separate line (we probably should have done so five options ago...

```python
def loopEvents(
        start=0,
        ....
        hitColour=None
    ):
```

2024-02-20 10:41 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
> +    if hitColour is not None :
```python
if hitColour:
    ...
```
should be sufficient, no? No space before the colon please.

2024-02-20 10:41 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
> +    if hitColour is not None :
Ditto:
```python
if hitColour:
    ...
```
should be sufficient, no? No space before the colon please.

2024-02-20 10:41 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
> +def fillNode(node, color = None):
No space around `=` in keyword argument

2024-02-20 16:17 UTC, cvilelahep commented on shipLHC/scripts/2dEventDisplay.py
> +ROOT.gStyle.SetPalette(ROOT.kViridis)
This should be fixed in issue #203.

2024-02-20 16:35 UTC, olantwin commented on shipLHC/scripts/2dEventDisplay.py
> +def loopEvents(start=0,save=False,goodEvents=False,withTrack=-1,withHoughTrack=-1,nTracks=0,minSipmMult=1,withTiming=False, option=None,Setup='',verbose=0,auto=False, hitColour = None):
In my example or the original?
This is what I get from the `ruff` formatter:
```python
def loopEvents(
    start=0,
    save=False,
    goodEvents=False,
    withTrack=-1,
    withHoughTrack=-1,
    nTracks=0,
    minSipmMult=1,
    withTiming=False,
    option=None,
    Setup="",
    verbose=0,
    auto=False,
    hitColour=None,
):
    pass
```
So indeed, I had indented everything one line too many. I barely remember how to do formatting manually :D

2024-02-20 16:37 UTC, olantwin commented
Appreciate the cleanup! Hopefully we can just move to automatically formatting code soon, so don't need to invest any work in making/keeping code readable.

2024-02-20 17:30 UTC, cvilelahep commented
Factorised the hit colour code into functions. @olantwin, I think that's all of the comments that could be implemented for now.

2024-02-20 20:45 UTC, olantwin approved these changes
Even with docstrings!
Consider my placated :)

PS: I might give #202 a shot when waiting for HTCondor jobs to finish one of the next days, now that I had a look at the `TPaletteAxis` docs.

2024-02-20 20:46 UTC, olantwin commented
Could you please rebase? I think the merge you did caused some conflicts.

2024-02-21 18:39 UTC, cvilelahep commented
Oops... should be ready to go now @olantwin

2024-02-21 21:42 UTC, olantwin approved these changes
Not sure how this ended up as 26 commits, I hope 24 of those will vanish on merge. The diff still looks OK.

2024-02-21 21:44 UTC, merged

2024-02-21 21:47 UTC, olantwin commented
@cvilelahep It would be great if you could avoid making merge commits next time. The history on main is a bit of a mess, with a lot of commits appearing twice or even thrice (well, it's more complicated than that. Essentially they appear once in each side of the history that was now merged).