Major revision of the Scifi digitization
SND-LHC/sndsw pull request #220
Opened 2024-05-09 11:09 UTC by siilieva

New lab measurements have been performed that led to an updated version of the Scifi digitization.
It is being described in an internal note.
Completely removed the old model since it's results are much more different from the data. 
For reference the presentations describing the comparisons between MC Scifi realizations and data are given below
https://indico.cern.ch/event/1394068/contributions/5893765/attachments/2830724/4945770/Software_news_3April2024.pdf
https://indico.cern.ch/event/1410259/contributions/5945569/attachments/2852834/4988435/Software_news_8May2024_new_Scifi_digi.pdf

2024-05-09 15:11 UTC, olantwin requested changes
1. I think some of the names are unnecessarily cryptic.
2. If the parameters are fixed anyway, we should probably make them static constants. We might also want to make sure that they are not serialised. Having a mutable copy per hit seems unnecessary. This would also simplify the method signatures.

2024-05-09 15:11 UTC, olantwin commented on shipLHC/sndScifiHit.cxx
> +Float_t sndScifiHit::ly_loss(Float_t distance, Float_t* params){
1. `light_yield_loss` or `light_attenuation`?
2. Could we please use a fixed-size array for params? It seems it is expected to be length 2?

2024-05-09 15:11 UTC, olantwin commented on shipLHC/sndScifiHit.cxx
> +Float_t sndScifiHit::sipm_saturation(Float_t ly, Float_t nphe_max){
Based on the comment, I would expect the return value to be an integer?

2024-05-09 15:11 UTC, olantwin commented on shipLHC/sndScifiHit.cxx
> +Float_t sndScifiHit::npix_to_qdc(Float_t npix, Float_t* params){
As above, let's use fixed-length arrays.

2024-05-09 15:11 UTC, olantwin commented on shipLHC/sndScifiHit.cxx
> +     Float_t Npix = sipm_saturation(ly_total,nphe_max);
Why is this not an integer?

2024-05-09 15:11 UTC, olantwin commented on shipLHC/sndScifiHit.h
> +	Float_t npix_to_qdc_params[4] = {0.172, -1.31, 0.006, 0.33}; // A, B, sigma_A, sigma_B
These should probably be static as they appear to be global constants?
In which case, I don't see the point of passing them as arguments to the different functions.

2024-06-07 07:33 UTC, siilieva commented on shipLHC/sndScifiHit.cxx
> +        Float_t ly = signal*1E+6*0.16; //0.16 p.e per 1 keV
`ly` is quite common abbreviation for light yield
If the future reader/user is in doubt the comment above explicitly reads "light yield"

2024-06-07 07:39 UTC, siilieva commented on shipLHC/sndScifiHit.cxx
> +Float_t sndScifiHit::ly_loss(Float_t distance, Float_t* params){
same for the ly_loss as above
2. good catch! I did a little research and it is suggested that the best practice for such internal class constants is an anonymous namespace, so I did that.

2024-06-07 07:39 UTC, siilieva commented on shipLHC/sndScifiHit.cxx
> +Float_t sndScifiHit::sipm_saturation(Float_t ly, Float_t nphe_max){
it could be non integer, same as the threshold in photo electrons is 3.5

2024-06-07 07:39 UTC, siilieva commented on shipLHC/sndScifiHit.cxx
> +Float_t sndScifiHit::npix_to_qdc(Float_t npix, Float_t* params){
anonymous namespace introduced.

2024-06-07 07:39 UTC, siilieva commented on shipLHC/sndScifiHit.cxx
> +     Float_t Npix = sipm_saturation(ly_total,nphe_max);
same as above
These are all internal calculations to get the QDC - better have non integer Npix etc. than lose precision of the final QDC.

2024-06-07 07:40 UTC, siilieva commented on shipLHC/sndScifiHit.h
> +	Float_t npix_to_qdc_params[4] = {0.172, -1.31, 0.006, 0.33}; // A, B, sigma_A, sigma_B
these are the fixed length params - placed in a namespace after the revision

2024-06-12 16:19 UTC, olantwin submitted a review, later dismissed
Looks good, the anonymous namespace makes things a lot tidier.

2024-06-12 16:19 UTC, olantwin commented on shipLHC/sndScifiHit.cxx
> +     Float_t npix_to_qdc_params[4] = {0.172, -1.31, 0.006, 0.33}; // A, B, sigma_A, sigma_B
We might want to make these constant.

2024-06-14 09:05 UTC, siilieva commented on shipLHC/sndScifiHit.cxx
> +     Float_t npix_to_qdc_params[4] = {0.172, -1.31, 0.006, 0.33}; // A, B, sigma_A, sigma_B
absolutely! I forgot to do it in the previous edit - doing now

2024-06-14 09:14 UTC, olantwin submitted a review, later dismissed

2024-06-19 10:15 UTC, siilieva commented
I believe another review is needed since there is a new commit  :innocent:

2024-06-19 11:11 UTC, olantwin approved these changes
I like that change to the copy constructor and assignment operator a lot!

2024-06-19 11:26 UTC, merged