Introduce possibility to run multi-source particle gun MC
SND-LHC/sndsw pull request #230
Opened 2024-06-21 06:39 UTC by siilieva

The concept is to have x-y planes at multiple Z slices along the beam direction serving as PG source.

2024-06-21 08:32 UTC, olantwin commented on shipLHC/run_simSND.py
> +parser.add_argument("--zSliceStep", dest="zSliceStep", help="distance between the Z slices for the PG sources", required=False, default=0, type=float)
A more sensible default here would be something non-zero  to avoid superimposed slices.

By the way, all of these don't need the `required=False` and `dest=`, as you are just respecifying the defaults.

2024-06-21 08:32 UTC, olantwin commented on shipLHC/run_simSND.py
> +parser.add_argument("--nZSlices", dest="nZSlices", help="number of Z slices for the PG sources", required=False, default=0, type=int)
The default here should be 1, as that's the default behaviour.

2024-06-21 08:51 UTC, siilieva commented on shipLHC/run_simSND.py
> +parser.add_argument("--zSliceStep", dest="zSliceStep", help="distance between the Z slices for the PG sources", required=False, default=0, type=float)
The point of the 0 default values for these parameters is that if the user doesn't specify them, point PG source is forced. Asking for multiple PG sources and putting `nZslices != 0` should go with a meaningful `zSliceStep` choice. Selecting `zSliceStep` is much goal specific and idk what would be a meaningful default case, nor have the time to find out. I am not willing to put a random number and have all users use that default just because they'll blindly think someone put care into selecting it.
Ok, for the `dest` and `required`  - I will wait for other remarks on Monday before pushing these.

2024-06-25 14:15 UTC, olantwin commented on shipLHC/run_simSND.py
> +parser.add_argument("--zSliceStep", dest="zSliceStep", help="distance between the Z slices for the PG sources", required=False, default=0, type=float)
You're right, there is no obvious default step. In that case, I would not have a default value at all.

2024-06-25 14:24 UTC, olantwin requested changes
Minor nit-picks, generally looks OK. Haven't had time to play around with it though.

2024-06-25 14:24 UTC, olantwin commented on shipLHC/run_simSND.py
> +    # multiple PG sources in the x-y plane; z is always the same!
I would add this note to the help message of that option.

2024-06-25 14:24 UTC, olantwin commented on shipLHC/run_simSND.py
> +                     options.EVz*u.cm)
Formatting.

2024-06-25 14:24 UTC, olantwin commented on shipLHC/run_simSND.py
> +  # For an !unknown! reason simply setting target Z thickness doesn't produce the desired result
What happens when it is set?

2024-07-09 08:26 UTC, siilieva commented on shipLHC/run_simSND.py
> +    # multiple PG sources in the x-y plane; z is always the same!
With these modifications the PG can have multiple sources in XY and also along Z. The way to do it has 2 steps: first one generates in XY and then a 2nd one moves along Z. And the comments aim to reflect just that. Then the help message is quite general  (help="multiple particle guns at various positions") as the code is quite flexible and can do plane PGs (XY@fixed Z) or 3D PGs with a XYZ spread.

2024-07-09 08:29 UTC, siilieva commented on shipLHC/run_simSND.py
> +  # For an !unknown! reason simply setting target Z thickness doesn't produce the desired result
no spread in Z is observed

2024-07-09 08:46 UTC, siilieva commented on shipLHC/run_simSND.py
> +    targetZpos = np.array(zSlices, dtype='d')
it does, nice

2024-07-09 08:56 UTC, olantwin commented on shipLHC/run_simSND.py
> +  # For an !unknown! reason simply setting target Z thickness doesn't produce the desired result
Then I would replace "the desired result" with "the expected spread in z"

2024-07-09 08:57 UTC, olantwin commented on shipLHC/run_simSND.py
> +  # For an !unknown! reason simply setting target Z thickness doesn't produce the desired result
Also, I'd stick to regular punctuation and maybe markdown formatting instead of inventing new methods of adding emphasis ;p

2024-07-09 09:04 UTC, siilieva commented on shipLHC/run_simSND.py
> +  # For an !unknown! reason simply setting target Z thickness doesn't produce the desired result
only cause I'm in a good mood :p:p

2024-07-09 09:06 UTC, olantwin commented on shipLHC/run_simSND.py
> +        ' and '+str(options.nZSlices)+' number of Z slices separated by '+str(options.zSliceStep)+'[cm].')
```suggestion
  print(f'===> Setting particle gun sources starting from (x1,y1,z1)=({
        options.EVx},{options.EVy},{options.EVz})[cm × cm × cm] \n'+
        f'with an x-y multiple of (Dx,Dy)=({options.Dx},{options.Dy})[cm × cm]'+
        f' and {options.nZSlices} number of Z slices separated by {options.zSliceStep}[cm].')
```

It's trivial to replace, and gives us more power in case we want to control how the numbers are converted to strings. I also replaced the xs with ×s, which was probably what was intended.

Concerning the message itself, I would say "starting at", with "x-y intervals of", and maybe "z slices in steps of". Even given the context, I wouldn't know what "multiple" is supposed to mean.
I would also suggest giving the steps in x/y as "𝛥x" and "𝛥y".

2024-07-09 09:09 UTC, olantwin commented on shipLHC/run_simSND.py
> +    # multiple PG sources in the x-y plane; z is always the same!
Honestly, this comment should then be the help message. The current one is really vague, and you just explained really concisely what the changes do :)

2024-07-09 09:29 UTC, olantwin commented on shipLHC/run_simSND.py
> +    # multiple PG sources in the x-y plane; z is always the same!
> I dont want three lines of text in the help

Why not? As long as things are reasonably formatted, I don't see a need to bend over backwards to make things fit one line.
Generally, it's good to be concise, but having two or three lines is in my opinion preferable to an overly short message.

That being said, your new proposed help message is much better than the previous one, and something I can live with. Two nitpicks:
1. I'd capitalise the first word
2. We should try to stick to upper or lowercase x,y,z everywhere. E.g. in the info message below, we use lowercase x,y.

2024-07-09 09:31 UTC, siilieva commented on shipLHC/run_simSND.py
> +        ' and '+str(options.nZSlices)+' number of Z slices separated by '+str(options.zSliceStep)+'[cm].')
I didn't know the code would accept ×! Nice!
I cannot commit the suggestion as it gives an error on the 1st line break. But copy-pasting and fixing the 1st line - it looks good, so I'd use your proposal.

In XY there is no interval setting, but plane dims setting - the text was initially unclear. So I propose
" with an x-y spread of size.." , ok for the rest of your suggested language changes

2024-07-09 09:38 UTC, olantwin commented on shipLHC/run_simSND.py
> +        ' and '+str(options.nZSlices)+' number of Z slices separated by '+str(options.zSliceStep)+'[cm].')
> I didn't know the code would accept ×!

Python 3 fully supports unicode. If we wanted to, we could use unicode for identifiers/variable names, but that's generally not considered a good practice.
In strings, I'd say we can use unicode as much as we like. (Same goes for things like ± etc.)

>Nice! I cannot commit the suggestion as it gives an error on the 1st line break. But copy-pasting and fixing the 1st line - it looks good, so I'd use your proposal.

Ah, I see the mistake, I'm not used to writing code in the github web interface :D

> In XY there is no interval setting, but plane dims setting - the text was initially unclear. So I propose " with an x-y spread of size.." , ok for the rest of your suggested language changes

Ah, then I misunderstood. What does the spread look like? If it's normal, I'd suggest using 𝜎x, otherwise Dx might not be all that bad...

2024-07-09 09:55 UTC, siilieva commented on shipLHC/run_simSND.py
> +        ' and '+str(options.nZSlices)+' number of Z slices separated by '+str(options.zSliceStep)+'[cm].')
ok, good to know about the unicode format.

the function uses [kBox](https://fairrootgroup.github.io/FairRoot/html/d7/d12/classFairBaseMCGenerator.html#a887af0393a72e37acda52aa59b822495) vertex(in our case point) smearing that is not Gaussian.
The resulting XY distribution looks rather uniform like this: 
![Screenshot from 2024-07-09 11-54-19](https://github.com/SND-LHC/sndsw/assets/84918585/240e539c-ac59-4f37-a9d6-d9641849c498)

2024-07-09 10:07 UTC, olantwin commented on shipLHC/run_simSND.py
> +        ' and '+str(options.nZSlices)+' number of Z slices separated by '+str(options.zSliceStep)+'[cm].')
Ah, good to know. May I suggest adding "uniform" in the help messages for the Dx and Dy arguments, and maybe this printout?

That plot could go into potential future documentation for the script ;)

2024-07-09 10:14 UTC, siilieva commented on shipLHC/run_simSND.py
> +        ' and '+str(options.nZSlices)+' number of Z slices separated by '+str(options.zSliceStep)+'[cm].')
done and done
 I force push the new version now

2024-07-09 10:28 UTC, olantwin commented on shipLHC/run_simSND.py
> +        f' and {options.nZSlices} z slices in steps of {options.zSliceStep}[cm].')
```suggestion
  print('===> Setting particle gun sources starting at (x1,y1,z1)='
        f'({options.EVx},{options.EVy},{options.EVz})[cm × cm × cm] \n'
        f'with a uniform x-y spread of (Dx,Dy)=({options.Dx},{options.Dy})[cm × cm]'
        f' and {options.nZSlices} z slices in steps of {options.zSliceStep}[cm].')
```
The +s are not needed, as we are within parentheses, so the string is just implicitly concatenated.

Would spacing around the commas and equals mess up the formatting? (In general, we could probably use automatic wrapping for logging, so that we don't need to worry about this, but no need to figure out how to do that now).

2024-07-09 10:29 UTC, olantwin submitted a review, later dismissed

2024-07-09 11:14 UTC, siilieva commented
committing the print message format suggestion triggered another Approval request.

2024-07-09 11:44 UTC, olantwin approved these changes

2024-07-09 11:45 UTC, olantwin commented
> committing the print message format suggestion triggered another Approval request.

You should be able to override it though, right?

2024-07-09 11:56 UTC, siilieva commented
> > committing the print message format suggestion triggered another Approval request.
> 
> You should be able to override it though, right?

What do you mean override? I was not able to approve. I can change the settings of the repo, force the PR and then change back to the usual.

2024-07-09 11:56 UTC, merged

2024-07-09 12:32 UTC, olantwin commented
At least I can bypass the approval requirements when merging things, without having to touch repository settings. I think as an admin you should also be able to do it.